name: 'Build & Publish'
on:
  push:
    branches:
      - main
    tags:
      - 3*

jobs:
  build-and-push:
    name: 'Build and Publish Docker Image'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Push Latest (Latest)
        uses: docker/build-push-action@v1
        if: github.ref == 'refs/heads/main'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: davidwesst/godot-mono
          tags: latest
      - name: Build and Push Latest (Tagged)
        uses: docker/build-push-action@v1
        if: contains( github.ref, 'tags' )
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: davidwesst/godot-mono
          tag_with_ref: true

