on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    name: Checkout Source
    steps:
      - name: Checkout
        uses: actions/checkout@v2

  

  # publish:
  #   needs: test-install
  #   runs-on: ubuntu-latest
  #   name: Publish Docker Image
  #   steps:
  #     - name: Build and push Docker images
  #       uses: docker/build-push-action@v1.1.0

